replicaCount: 2
image:
  repository: ghcr.io/example/freedom-bot
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 3000
env:
  BOT_TOKEN: ""
  WEBHOOK_DOMAIN: ""
  WEBHOOK_SECRET: ""
  DATABASE_URL: ""
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: freedom-bot.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
