apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freedom-bot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "freedom-bot.name" . }}
    helm.sh/chart: {{ include "freedom-bot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "freedom-bot.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "freedom-bot.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "freedom-bot.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: BOT_TOKEN
              value: {{ .Values.env.BOT_TOKEN | quote }}
            - name: WEBHOOK_DOMAIN
              value: {{ .Values.env.WEBHOOK_DOMAIN | quote }}
            - name: WEBHOOK_SECRET
              value: {{ .Values.env.WEBHOOK_SECRET | quote }}
            - name: DATABASE_URL
              value: {{ .Values.env.DATABASE_URL | quote }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
